# Generated by Django 4.2.7 on 2026-05-10

import uuid
from django.db import migrations, models


def populate_share_tokens(apps, schema_editor):
    Trip = apps.get_model('trips', 'Trip')
    for trip in Trip.objects.filter(share_token__isnull=True):
        trip.share_token = uuid.uuid4()
        trip.save(update_fields=['share_token'])


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_invoice_invoiceitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trip',
            name='share_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.RunPython(populate_share_tokens, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='trip',
            name='share_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
